# Generated by Django 4.2.2 on 2023-09-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_cartitem_quantity_cartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
