# Generated by Django 4.2.2 on 2023-09-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_ordermodel_date_of_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
    ]
