# Generated by Django 4.2.2 on 2023-09-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_ordermodel_items_alter_ordermodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order', to='customer.menuitem'),
        ),
    ]
