# Generated by Django 4.2.2 on 2023-09-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
